### ISSUE TITLE
MeeShop 0.2.0 stucks at "building databases..." or "Importing necessary modules..."

### ISSUE THREAD

**Issue by ferlanero** [WunderWungiel/MeeShop#1]
Installing Meeshop 0.2.0 everything goes ok.

When launching I get:

```
Setting up workspace...
Done!
Testing internet connection...
Done!
Building databases...
```

And it doesn't go further most of times.

Other times:

```
Setting up workspace...
Done!
Testing internet connection...
Done!
Building databases...
Done!
Importing necessary modules...
```

And it doesn't go further.

Early versions seem to work better

**Comment by WunderWungiel** [comment]
@ferlanero Hmm. Installed with aegis-dpkg? I just removed all cached XMLs from my device and ran MeeShop v0.2.0, works fine.  
 
Importing modules and building databases often take much time.

**Comment by ferlanero** [comment]
Thanks for your quickly answer! Uninstalling Meeshop 0.2.0 and reinstaling it again seems to fix the problem. Now everything is working as expected!

**Comment by WunderWungiel** [comment]
@ferlanero Great! Glad it works for you now.
