### ISSUE TITLE
Are there plans to add a GUI?

### ISSUE THREAD

**Issue by IdotMaster1** [WunderWungiel/MeeShop#2]

**Comment by IarChep** [comment]
GUI is already ready
Link: https://github.com/YaroslavChepel/MeeShopGUI

**Comment by WunderWungiel** [comment]
@YaroslavChepel But has less functions and is still WIP... But more comfortable, anyway

**Comment by IdotMaster1** [comment]
I didint even see it @YaroslavChepel, thanks!
